"""Pack named ROM blobs at the end of a fixed-size Mega Drive image.

Blobs are placed contiguously just before the ROM end, in the order given: the
last blob occupies the absolute end of the image (matching the historical
tile-at-end layout). Each blob is padded to its alignment. The unused prefix
remains 0xFF.

This module is intentionally data-only: callers supply blob bytes and consume
the layout dict / generated C++ header.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROM_SIZE = 4 * 1024 * 1024


@dataclass(frozen=True)
class AssetBlob:
    """One named payload embedded in the asset ROM."""

    name: str
    data: bytes
    align: int = 2

    def __post_init__(self) -> None:
        if self.align < 1 or (self.align & (self.align - 1)) != 0:
            raise ValueError(f"align must be a power of two, got {self.align}")
        if not self.name.isidentifier():
            raise ValueError(f"blob name must be a C identifier: {self.name!r}")


@dataclass(frozen=True)
class PackedBlob:
    name: str
    offset: int
    size: int
    aligned_size: int


@dataclass(frozen=True)
class AssetLayout:
    rom_size: int
    pack_offset: int
    pack_size: int
    blobs: tuple[PackedBlob, ...]

    def blob(self, name: str) -> PackedBlob:
        for entry in self.blobs:
            if entry.name == name:
                return entry
        raise KeyError(name)

    def to_json(self) -> dict:
        return {
            "rom_size": self.rom_size,
            "pack_offset": self.pack_offset,
            "pack_size": self.pack_size,
            "blobs": [
                {
                    "name": blob.name,
                    "offset": blob.offset,
                    "size": blob.size,
                    "aligned_size": blob.aligned_size,
                }
                for blob in self.blobs
            ],
        }

    @staticmethod
    def from_json(data: dict) -> AssetLayout:
        blobs = tuple(
            PackedBlob(
                name=str(entry["name"]),
                offset=int(entry["offset"]),
                size=int(entry["size"]),
                aligned_size=int(entry["aligned_size"]),
            )
            for entry in data["blobs"]
        )
        return AssetLayout(
            rom_size=int(data["rom_size"]),
            pack_offset=int(data["pack_offset"]),
            pack_size=int(data["pack_size"]),
            blobs=blobs,
        )


def _align_up(value: int, align: int) -> int:
    return (value + align - 1) & ~(align - 1)


def pack_blobs(blobs: Iterable[AssetBlob], *, rom_size: int = ROM_SIZE) -> tuple[bytes, AssetLayout]:
    """Pack blobs at the end of a rom_size image. Last blob ends at rom_size."""
    ordered = list(blobs)
    if not ordered:
        raise ValueError("at least one asset blob is required")

    # Build from the end so the final blob sits at rom_size.
    cursor = rom_size
    packed_reversed: list[tuple[AssetBlob, int, int, bytes]] = []
    for blob in reversed(ordered):
        aligned_size = _align_up(len(blob.data), blob.align)
        cursor -= aligned_size
        if cursor < 0:
            raise ValueError("asset blobs do not fit in the ROM image")
        payload = blob.data + bytes(aligned_size - len(blob.data))
        packed_reversed.append((blob, cursor, aligned_size, payload))

    pack_offset = cursor
    pack_size = rom_size - pack_offset
    image = bytearray([0xFF]) * rom_size
    layout_blobs: list[PackedBlob] = []

    for blob, offset, aligned_size, payload in reversed(packed_reversed):
        image[offset : offset + aligned_size] = payload
        layout_blobs.append(
            PackedBlob(
                name=blob.name,
                offset=offset,
                size=len(blob.data),
                aligned_size=aligned_size,
            )
        )

    layout = AssetLayout(
        rom_size=rom_size,
        pack_offset=pack_offset,
        pack_size=pack_size,
        blobs=tuple(layout_blobs),
    )
    return bytes(image), layout


def write_layout_json(layout: AssetLayout, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(layout.to_json(), indent=2) + "\n", encoding="utf-8")


def write_layout_header(layout: AssetLayout, path: Path) -> None:
    """Emit a freestanding-friendly C++ header with blob offsets and sizes."""
    lines = [
        "#pragma once",
        "",
        "/**",
        " * @file AssetLayout.hpp",
        " * Generated by tools/build_assets.py — do not edit.",
        " */",
        "",
        "namespace sample::assets {",
        "",
        f"inline constexpr unsigned kRomSize = {layout.rom_size}u;",
        f"inline constexpr unsigned kPackOffset = {layout.pack_offset}u;",
        f"inline constexpr unsigned kPackSize = {layout.pack_size}u;",
        "",
    ]
    for blob in layout.blobs:
        camel = "".join(part.title() for part in blob.name.split("_"))
        lines.append(f"inline constexpr unsigned k{camel}Offset = {blob.offset}u;")
        lines.append(f"inline constexpr unsigned k{camel}Size = {blob.size}u;")
        lines.append(f"inline constexpr unsigned k{camel}AlignedSize = {blob.aligned_size}u;")
        lines.append("")
    lines.append("} // namespace sample::assets")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_pack_binary(image: bytes, layout: AssetLayout, path: Path) -> None:
    """Write only the packed tail used by the real-hardware .assets section."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(image[layout.pack_offset :])
