"""Pack named ROM blobs at the end of a fixed-size Mega Drive image.

Blobs are placed contiguously just before the ROM end, in the order given: the
last blob occupies the absolute end of the image (matching the historical
tile-at-end layout). Each blob is padded to its alignment. The unused prefix
remains 0xFF.

This module is intentionally data-only: callers supply blob bytes and consume
the layout dict / generated C++ header.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROM_SIZE = 4 * 1024 * 1024


@dataclass(frozen=True)
class AssetBlob:
    """One named payload embedded in the asset ROM."""

    name: str
    data: bytes
    align: int = 2

    def __post_init__(self) -> None:
        if self.align < 1 or (self.align & (self.align - 1)) != 0:
            raise ValueError(f"align must be a power of two, got {self.align}")
        if not self.name.isidentifier():
            raise ValueError(f"blob name must be a C identifier: {self.name!r}")


@dataclass(frozen=True)
class PackedBlob:
    name: str
    offset: int
    size: int
    aligned_size: int


@dataclass(frozen=True)
class AssetLayout:
    rom_size: int
    pack_offset: int
    pack_size: int
    blobs: tuple[PackedBlob, ...]

    def blob(self, name: str) -> PackedBlob:
        for entry in self.blobs:
            if entry.name == name:
                return entry
        raise KeyError(name)

    def to_json(self) -> dict:
        return {
            "rom_size": self.rom_size,
            "pack_offset": self.pack_offset,
            "pack_size": self.pack_size,
            "blobs": [
                {
                    "name": blob.name,
                    "offset": blob.offset,
                    "size": blob.size,
                    "aligned_size": blob.aligned_size,
                }
                for blob in self.blobs
            ],
        }

    @staticmethod
    def from_json(data: dict) -> AssetLayout:
        blobs = tuple(
            PackedBlob(
                name=str(entry["name"]),
                offset=int(entry["offset"]),
                size=int(entry["size"]),
                aligned_size=int(entry["aligned_size"]),
            )
            for entry in data["blobs"]
        )
        return AssetLayout(
            rom_size=int(data["rom_size"]),
            pack_offset=int(data["pack_offset"]),
            pack_size=int(data["pack_size"]),
            blobs=blobs,
        )


def _align_up(value: int, align: int) -> int:
    return (value + align - 1) & ~(align - 1)


def pack_blobs(blobs: Iterable[AssetBlob], *, rom_size: int = ROM_SIZE) -> tuple[bytes, AssetLayout]:
    """Pack blobs at the end of a rom_size image. Last blob ends at rom_size."""
    ordered = list(blobs)
    if not ordered:
        raise ValueError("at least one asset blob is required")

    # Build from the end so the final blob sits at rom_size.
    cursor = rom_size
    packed_reversed: list[tuple[AssetBlob, int, int, bytes]] = []
    for blob in reversed(ordered):
        aligned_size = _align_up(len(blob.data), blob.align)
        cursor -= aligned_size
        if cursor < 0:
            raise ValueError("asset blobs do not fit in the ROM image")
        payload = blob.data + bytes(aligned_size - len(blob.data))
        packed_reversed.append((blob, cursor, aligned_size, payload))

    pack_offset = cursor
    pack_size = rom_size - pack_offset
    image = bytearray([0xFF]) * rom_size
    layout_blobs: list[PackedBlob] = []

    for blob, offset, aligned_size, payload in reversed(packed_reversed):
        image[offset : offset + aligned_size] = payload
        layout_blobs.append(
            PackedBlob(
                name=blob.name,
                offset=offset,
                size=len(blob.data),
                aligned_size=aligned_size,
            )
        )

    layout = AssetLayout(
        rom_size=rom_size,
        pack_offset=pack_offset,
        pack_size=pack_size,
        blobs=tuple(layout_blobs),
    )
    return bytes(image), layout


def write_layout_json(layout: AssetLayout, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(layout.to_json(), indent=2) + "\n", encoding="utf-8")


def write_layout_header(layout: AssetLayout, path: Path) -> None:
    """Emit a freestanding-friendly C++ header with blob offsets and sizes."""
    lines = [
        "#pragma once",
        "",
        "/**",
        " * @file AssetLayout.hpp",
        " * Generated by tools/build_assets.py — do not edit.",
        " */",
        "",
        "namespace sample::assets {",
        "",
        f"inline constexpr unsigned kRomSize = {layout.rom_size}u;",
        f"inline constexpr unsigned kPackOffset = {layout.pack_offset}u;",
        f"inline constexpr unsigned kPackSize = {layout.pack_size}u;",
        "",
    ]
    for blob in layout.blobs:
        camel = "".join(part.title() for part in blob.name.split("_"))
        lines.append(f"inline constexpr unsigned k{camel}Offset = {blob.offset}u;")
        lines.append(f"inline constexpr unsigned k{camel}Size = {blob.size}u;")
        lines.append(f"inline constexpr unsigned k{camel}AlignedSize = {blob.aligned_size}u;")
        lines.append("")
    lines.append("} // namespace sample::assets")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_pack_binary(image: bytes, layout: AssetLayout, path: Path) -> None:
    """Write only the packed tail used by the real-hardware .assets section."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(image[layout.pack_offset :])


def format_byte_size(size: int) -> str:
    """Human-readable size with hex, for build logs."""
    if size >= 1024:
        return f"{size} bytes (0x{size:X}, {size / 1024:.1f} KiB)"
    return f"{size} bytes (0x{size:X})"


@dataclass(frozen=True)
class RomRegion:
    """Named slice of the cartridge image for text/SVG charts."""

    name: str
    offset: int
    size: int
    color: str  # CSS / SVG fill colour
    glyph: str  # single character for ASCII stacked maps


def _bar(fraction: float, width: int = 40, fill: str = "█", empty: str = "·") -> str:
    filled = int(round(max(0.0, min(1.0, fraction)) * width))
    filled = max(0, min(width, filled))
    if fraction > 0 and filled == 0:
        filled = 1
    return fill * filled + empty * (width - filled)


def _stacked_ascii(regions: list[RomRegion], total: int, width: int = 56) -> str:
    """One-line map of the full ROM (or used span) using per-region glyphs."""
    if total <= 0:
        return ""
    cells: list[str] = []
    for region in regions:
        if region.size <= 0:
            continue
        n = max(1, int(round(region.size / total * width)))
        cells.append(region.glyph * n)
    line = "".join(cells)
    if len(line) < width:
        line += "·" * (width - len(line))
    elif len(line) > width:
        line = line[:width]
    return f"  [{line}]"


def _print_region_rows(regions: list[RomRegion], *, bar_width: int = 36) -> None:
    positive = [r for r in regions if r.size > 0]
    scale = max((r.size for r in positive), default=1)
    for region in positive:
        end = region.offset + region.size - 1
        pct = 100.0 * region.size / scale if scale else 0.0
        # Per-row bar is relative to the largest region for readability.
        print(
            f"  {region.glyph} {region.name + ':':20} {_bar(region.size / scale, bar_width)} "
            f"{format_byte_size(region.size)}  "
            f"[0x{region.offset:06X}-0x{end:06X}]"
        )


def _write_rom_layout_svg(
    path: Path,
    *,
    title: str,
    rom_size: int,
    full_regions: list[RomRegion],
    used_regions: list[RomRegion],
) -> None:
    """Write a simple two-panel SVG chart of the ROM layout."""
    path.parent.mkdir(parents=True, exist_ok=True)
    width = 720
    margin = 24
    bar_h = 36
    y0 = 56
    y1 = 160
    inner_w = width - 2 * margin

    def segments(regions: list[RomRegion], total: int) -> list[tuple[RomRegion, float, float]]:
        out: list[tuple[RomRegion, float, float]] = []
        x = 0.0
        for region in regions:
            if region.size <= 0 or total <= 0:
                continue
            w = max(1.0, region.size / total * inner_w)
            out.append((region, x, w))
            x += w
        return out

    used_total = sum(r.size for r in used_regions if r.size > 0)
    full_segs = segments(full_regions, rom_size)
    used_segs = segments(used_regions, used_total or 1)

    legend_items = []
    seen: set[str] = set()
    for region in full_regions + used_regions:
        if region.name in seen or region.size <= 0:
            continue
        seen.add(region.name)
        legend_items.append(region)

    legend_y = y1 + bar_h + 36
    svg: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{legend_y + 28 + 22 * len(legend_items)}" '
        f'viewBox="0 0 {width} {legend_y + 28 + 22 * len(legend_items)}">',
        f'<rect width="100%" height="100%" fill="#0f1115"/>',
        f'<text x="{margin}" y="28" fill="#e8eaed" font-family="ui-sans-serif,system-ui,sans-serif" '
        f'font-size="16" font-weight="600">{title}</text>',
        f'<text x="{margin}" y="{y0 - 10}" fill="#9aa0a6" font-family="ui-sans-serif,system-ui,sans-serif" '
        f'font-size="12">Full 4 MiB cart (linear)</text>',
        f'<rect x="{margin}" y="{y0}" width="{inner_w}" height="{bar_h}" rx="4" fill="#1a1d24" '
        f'stroke="#3c4048"/>',
    ]
    for region, x, w in full_segs:
        svg.append(
            f'<rect x="{margin + x:.1f}" y="{y0}" width="{w:.1f}" height="{bar_h}" '
            f'fill="{region.color}"><title>{region.name}: {region.size} bytes</title></rect>'
        )
    svg.append(
        f'<text x="{margin}" y="{y1 - 10}" fill="#9aa0a6" font-family="ui-sans-serif,system-ui,sans-serif" '
        f'font-size="12">Used only (header + code + assets, scaled)</text>'
    )
    svg.append(
        f'<rect x="{margin}" y="{y1}" width="{inner_w}" height="{bar_h}" rx="4" fill="#1a1d24" '
        f'stroke="#3c4048"/>'
    )
    for region, x, w in used_segs:
        svg.append(
            f'<rect x="{margin + x:.1f}" y="{y1}" width="{w:.1f}" height="{bar_h}" '
            f'fill="{region.color}"><title>{region.name}: {region.size} bytes</title></rect>'
        )

    svg.append(
        f'<text x="{margin}" y="{legend_y}" fill="#9aa0a6" font-family="ui-sans-serif,system-ui,sans-serif" '
        f'font-size="12">Legend</text>'
    )
    for i, region in enumerate(legend_items):
        ly = legend_y + 18 + i * 22
        svg.append(f'<rect x="{margin}" y="{ly - 10}" width="14" height="14" rx="2" fill="{region.color}"/>')
        svg.append(
            f'<text x="{margin + 22}" y="{ly + 2}" fill="#e8eaed" '
            f'font-family="ui-sans-serif,system-ui,sans-serif" font-size="12">'
            f"{region.name}: {format_byte_size(region.size)}</text>"
        )
    svg.append("</svg>\n")
    path.write_text("".join(svg), encoding="utf-8")


def print_asset_layout_summary(
    layout: AssetLayout,
    *,
    title: str = "Asset pack",
    svg_path: Path | None = None,
) -> None:
    """Print pack offset/size, each blob, and a visual map."""
    free_prefix = layout.pack_offset
    free_region = RomRegion("free", 0, free_prefix, "#3c4048", "·")
    asset_colors = ("#8ab4f8", "#fdd663", "#81c995", "#f28b82", "#c58af9")
    asset_glyphs = "ABCDEFGH"
    full_regions: list[RomRegion] = [free_region]
    used_regions: list[RomRegion] = []
    for index, blob in enumerate(layout.blobs):
        region = RomRegion(
            blob.name,
            blob.offset,
            blob.aligned_size,
            asset_colors[index % len(asset_colors)],
            asset_glyphs[index % len(asset_glyphs)],
        )
        full_regions.append(region)
        used_regions.append(
            RomRegion(blob.name, blob.offset, blob.size, region.color, region.glyph)
        )

    print(f"{title}:")
    print(f"  ROM size:              {format_byte_size(layout.rom_size)}")
    print(
        f"  Free before assets:    {format_byte_size(free_prefix)}  "
        f"[0x000000-0x{layout.pack_offset - 1:06X}]"
    )
    print(
        f"  Assets (packed):       {format_byte_size(layout.pack_size)}  "
        f"[0x{layout.pack_offset:06X}-0x{layout.rom_size - 1:06X}]"
    )
    for blob in layout.blobs:
        end = blob.offset + blob.aligned_size - 1
        pad = blob.aligned_size - blob.size
        pad_note = f", pad {pad}" if pad else ""
        print(
            f"    {blob.name + ':':22} {format_byte_size(blob.size)}  "
            f"[0x{blob.offset:06X}-0x{end:06X}]{pad_note}"
        )

    print("  Full cart map (linear):")
    print(_stacked_ascii(full_regions, layout.rom_size))
    print("  Assets detail (relative bars):")
    _print_region_rows(used_regions)

    if svg_path is not None:
        _write_rom_layout_svg(
            svg_path,
            title=title,
            rom_size=layout.rom_size,
            full_regions=full_regions,
            used_regions=used_regions,
        )
        print(f"  Chart: {svg_path}")


def print_megadrive_rom_summary(
    layout: AssetLayout,
    *,
    code_end: int,
    title: str = "Mega Drive ROM layout",
    svg_path: Path | None = None,
) -> None:
    """Print vectors/header, code, free gap, asset pack, and visual charts."""
    vectors_size = 0x100
    header_size = 0x100
    header_region = vectors_size + header_size  # 0x000000-0x0001FF
    code_start = 0x200
    if code_end < code_start:
        raise ValueError(f"code_end 0x{code_end:X} is before code start 0x{code_start:X}")
    if code_end > layout.pack_offset:
        raise ValueError(
            f"code_end 0x{code_end:X} overlaps assets at 0x{layout.pack_offset:X}"
        )
    code_size = code_end - code_start
    free_gap = layout.pack_offset - code_end
    used = header_region + code_size + layout.pack_size
    free_total = layout.rom_size - used

    header = RomRegion("header", 0, header_region, "#f28b82", "H")
    code = RomRegion("code", code_start, code_size, "#8ab4f8", "C")
    free = RomRegion("free", code_end, free_gap, "#3c4048", "·")
    assets = RomRegion("assets", layout.pack_offset, layout.pack_size, "#fdd663", "A")
    full_regions = [header, code, free, assets]

    asset_colors = ("#fdd663", "#81c995", "#c58af9", "#78d9ec", "#f28b82")
    asset_glyphs = "abcdef"
    used_regions: list[RomRegion] = [header, code]
    for index, blob in enumerate(layout.blobs):
        used_regions.append(
            RomRegion(
                blob.name,
                blob.offset,
                blob.size,
                asset_colors[index % len(asset_colors)],
                asset_glyphs[index % len(asset_glyphs)],
            )
        )

    print(f"{title}:")
    print(f"  ROM size:              {format_byte_size(layout.rom_size)}")
    print(
        f"  Header (vectors+Sega): {format_byte_size(header_region)}  "
        f"[0x000000-0x0001FF]  (vectors {vectors_size}, rom_header {header_size})"
    )
    print(
        f"  Code (startup+text):   {format_byte_size(code_size)}  "
        f"[0x{code_start:06X}-0x{code_end - 1:06X}]"
    )
    if free_gap:
        print(
            f"  Free gap (to assets):  {format_byte_size(free_gap)}  "
            f"[0x{code_end:06X}-0x{layout.pack_offset - 1:06X}]"
        )
    print(
        f"  Assets (packed):       {format_byte_size(layout.pack_size)}  "
        f"[0x{layout.pack_offset:06X}-0x{layout.rom_size - 1:06X}]"
    )
    for blob in layout.blobs:
        end = blob.offset + blob.aligned_size - 1
        print(
            f"    {blob.name + ':':22} {format_byte_size(blob.size)}  "
            f"[0x{blob.offset:06X}-0x{end:06X}]"
        )
    print(f"  Used (header+code+assets): {format_byte_size(used)}")
    print(f"  Free total:                {format_byte_size(free_total)}")

    print("  Full cart map (H=header C=code ·=free A=assets):")
    print(_stacked_ascii(full_regions, layout.rom_size))
    print("  Used breakdown (relative bars):")
    _print_region_rows(used_regions)

    if svg_path is not None:
        _write_rom_layout_svg(
            svg_path,
            title=title,
            rom_size=layout.rom_size,
            full_regions=full_regions,
            used_regions=used_regions,
        )
        print(f"  Chart: {svg_path}")
